services:
  server_1:
    build: .
    environment:
      PORT: "8000"
      HOST: "127.0.0.1"
    networks:
    - task
 
  server_2:
    build: .
    environment:
      PORT: "8001"
      HOST: "127.0.0.1"
    networks:
    - task

  nginx_1:
    container_name: nginx_proxy_1
    build: ./nginx
    ports:
      - "81:80"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/keepalived-master.conf:/etc/keepalived/keepalived.conf"
    networks:
      - task

  nginx_2:
    container_name: nginx_proxy_2
    build: ./nginx
    ports:
      - "80:80"
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - NET_RAW
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./nginx/keepalived-backup.conf:/etc/keepalived/keepalived.conf"
    networks:
      - task

networks:
  task:
    driver: bridge