apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../../base
- env-secret.yaml # This shouldn't be stored in the repository. It is stored in a sealed secret in a git repo

images:
- name: saidimtaylan/sample-hello-there
  newTag: "v2" # this tag will change dynamically by a CI platform like jenkins. This is for CD platforms such as Flux or ArgoCD.